ProiectV1/Models/Request.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProiectV1.Models
{
    public class Request
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Titlul produsului este obligatoriu!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Descrierea produsului este obligatorie!")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Pretul produsului este obligatoriu!")]
        [Range(1, int.MaxValue, ErrorMessage = "Pretul trebuie sa fie cel putin 1")]
        public int Price { get; set;}

        //adaugam requirements mai tz, momentan vrem sa vedem daca functioneaza overall
        //[Required(ErrorMessage = "Este obligatorie adaugarea unei poze pentru produs!")]
        public string? PictureUrl { get; set; } //aici ar tb fara ?

        


        public double? Rating { get; set; } //aici ar tb fara ? (in caz ca nu s-a dat niciun rating se afiseaza 0.00

        //detalii legate de request- status + data adaugarii
        public string? Status { get; set; }
        public DateTime Date { get; set; }  // data va fi preluata direct din sistem la momentul adaugarii unui request

        [Required(ErrorMessage = "Categoria din care face produsul este obligatorie!")]
        public int? CategoryId { get; set; } //FK
        public virtual Category? Category { get; set; } //facem join cu tabela Category


        // user-ul care face cererea de publicare a produsului in magazin
        public string? UserId { get; set; } // FK 
        public virtual ApplicationUser? User { get; set; }


        [NotMapped]
        public IEnumerable<SelectListItem>? Categ { get; set; }

        // Constructor care initializeaza data cu cea din server
        public Request()
        {
            Date = DateTime.Now;
            Status = "Pending";
        }

    }
}

ProiectV1/Controllers/RequestsController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProiectV1.Data;
using ProiectV1.Models;
using System;

namespace ProiectV1.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly IWebHostEnvironment _env;

        public RequestsController(
                ApplicationDbContext context,
                UserManager<ApplicationUser> userManager,
                RoleManager<IdentityRole> roleManager,
                IWebHostEnvironment env)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }


        public IActionResult Index()
        {
            return View();
        }

        //functia cu ajutorul careia facem pagina(view) in care Colaboratorul vede toate request-urile trimise doar de el

        [Authorize(Roles = "Colaborator")]
        public IActionResult IndexColaborator()
        {
            // Alegem sa afisam 3 cereri pe pagina
            int _perPage = 3;

            // Obtinem id-ul colaboratorului curent
            string currentUserId = _userManager.GetUserId(User);
            // Filtram request-urile pentru a le afisa doar pe cele ale colaboratorului curent
            var requests = db.Requests.Include("Category").Include("User")
                               .Where(req => req.UserId == currentUserId);

            ViewBag.Requests = requests; //stocam request-urile filtrate

            if (TempData.ContainsKey("message")) 
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            var search = "";
            // MOTOR DE CAUTARE
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {

                // eliminam spatiile libere
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();
                // Cautare in articol (Title)
                // Cautare in articol (Title)
                List<int> articleIds = db.Requests
                    .Where(at => at.Title.Contains(search))
                    .Select(a => a.Id)
                    .ToList();



                // Lista articolelor care contin cuvantul cautat
                // fie in articol -> Title si Content
                // fie in comentarii -> Content
                requests = db.Requests.Where(request =>
                        articleIds.Contains(request.Id))
                                .Include("Category")
                                .Include("User");
            }
            ViewBag.SearchString = search;

            // Fiind un numar variabil de cereri, verificam de fiecare data utilizand metoda Count()
            int totalItems = requests.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta /Requests/IndexColaborator?page=valoare
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3
            // Asadar offsetul este egal cu numarul de cereri care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau cererile corespunzatoare pentru fiecare pagina la care ne aflam in functie de offset
            var paginatedRequests = requests.Skip(offset).Take(_perPage);

            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem cererile cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Requests = paginatedRequests;

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/Requests/Index/?search="
                + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Requests/Index/?page";
            }

            return View();
        }

        //HttpGet implicit
        //Functia de afisare a unui request pentru un produs (cu toate datele pe care le contine produsul
        //Momentan din View afisam doar titlu, descriere, data si cn a facut cererea (mai tarziu o sa adaugam si poza si alte detalii), momentan e strict pt functionalitate
        [Authorize(Roles = "Colaborator")]
        public IActionResult ShowColaborator(int id)
        {
            Request request = db.Requests.Include("Category")
                                         .Include("User") //join cu tabelele category si user
                               .Where(req => req.Id == id) //deci selectam request-urile avand si informatiile auxiliare legate de categorie si user-ul care a creat request
                               .First(); 

            return View(request);
        }


        //HttpGet implicit
        //Functia de adaugare a unui nou request de catre colaborator
        [Authorize(Roles = "Colaborator")]
        public IActionResult New()
        {
            Request request = new Request(); //crearea unui nou obiect de tip request

            request.Categ = GetAllCategories(); //in Categ stocam toate categoriile existente pentru a putea face in view dropdown(pt ca user-ul sa selecteze din el ce vrea)

            return View(request);
        }

        // Se adauga requestul in baza de date
        // Doar utilizatorii cu rolul de Colaborator pot face request-uri in platforma

        [Authorize(Roles = "Colaborator")]
        [HttpPost]
        public async Task<IActionResult> New(Request request, IFormFile imageFile)
        {
            var sanitizer = new HtmlSanitizer();

            request.Date = DateTime.Now;
            request.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                request.Description = sanitizer.Sanitize(request.Description);

                if (imageFile != null && imageFile.Length > 0)
                {
                    var storagePath = Path.Combine(
                        _env.WebRootPath,
                        "images",
                        imageFile.FileName
                    );

                    request.PictureUrl = "/images/" + imageFile.FileName;

                    using (var fileStream = new FileStream(storagePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);
                    }
                }

                db.Requests.Add(request);
                await db.SaveChangesAsync();

                TempData["message"] = "Cererea a fost trimisă către administrator!";
                TempData["messageType"] = "alert-success";

                return RedirectToAction("IndexColaborator");
            }
            else
            {
                request.Categ = GetAllCategories();
                return View(request);
            }
        }



        //functia cu ajutorul careia facem pagina(view) in care Adminul vede toate request-urile primite de la Colaboratori
        //am implementat si in partea de layout vizualizarea ei
        [Authorize(Roles = "Admin")]
        public IActionResult IndexAdmin()
        {
            // Alegem sa afisam 3 cereri pe pagina
            int _perPage = 3;

            var requests = db.Requests.Include("Category").Include("User")
                                        .Where(req => req.Status == "Pending"); //facem asta pentru a afisa paginat doar request-urile in asteptare 
            ViewBag.Requests = requests; //stocam request-urile

   
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            // Fiind un numar variabil de cereri, verificam de fiecare data utilizand metoda Count()
            int totalItems = requests.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta /Requests/IndexColaborator?page=valoare
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3
            // Asadar offsetul este egal cu numarul de cereri care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau cererile corespunzatoare pentru fiecare pagina la care ne aflam in functie de offset
            var paginatedRequests = requests.Skip(offset).Take(_perPage);

            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem cererile cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Requests = paginatedRequests;


            return View();
        }

        //se putea face si acelasi show pt colaborator si admin cu ascundere de butoane in functie de rol, dar am implementat asa in caz ca
                //devine mai complicat si mai diferit show-ul mai tarziu

ProiectV1/Views/Requests/IndexAdmin.cshtml
@*Pagina pe care o vede administratorul cand vrea sa vizualizeze toate cererile pe care le-a primit*@

@{
    ViewBag.Title = "Index";
}

<br />

<h2 class="text-center">Afisare cereri</h2>

<br />

@if (ViewBag.Message != null)
{
    <div class="@ViewBag.Alert p-3 rounded-3 text-center mb-5">@ViewBag.Message</div>
}
<br />

<br />


@foreach (ProiectV1.Models.Request request in ViewBag.Requests)
{
    if (request.Status == "Pending")
    {
        <div class="card">
            <div class="card-body">


                <h3 class="card-title alert-success py-3 px-3 rounded-2">@request.Title</h3>



                <div class="d-flex justify-content-between flex-row mt-5">

                    <div><i class="bi bi-globe"></i> @request.Category.CategoryName</div>


                    <span class="alert-success">
                        <div>@request.Date</div>
                        <div><i class="bi bi-person"></i> @request.User.UserName </div>
                    </span>

                </div>
                <div class="d-flex justify-content-between flex-row mt-5">

                    <div class="d-flex justify-content-between flex-row mt-5">
                        <div>
                            <form asp-action="Approve" method="post">
                                <input type="hidden" name="id" value="@request.Id" />
                                <button type="submit" class="btn btn-success">Acceptare cerere</button>
                            </form>
                        </div>

                        <div>
                            <a class="btn btn-success" href="/Requests/ShowAdmin/@request.Id">Afisare cerere</a>
                        </div>
                   
                        <div>
                            <form asp-action="Reject" method="post">
                                <input type="hidden" name="id" value="@request.Id" />
                                <button type="submit" class="btn btn-danger">Refuzare cerere</button>
                            </form>
                        </div>
                    </div>

                </div>


            </div>
        </div>
        <br />
    }
}

<br />
<br />

@* Afisarea paginata a cererilor *@
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link"
                   href="/Requests/IndexAdmin?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.lastPage; i++)
            {
                <li class="page-item">
                    <a class="page-link"
                       href="/Requests/IndexAdmin?page=@i">@(i)</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link"
                   href="/Requests/IndexAdmin?page=@(ViewBag.lastPage)" aria-
                   label="Next">

                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<br />
<br />

ProiectV1/Views/Requests/IndexColaborator.cshtml
@*Pagina pe care o vede colaboratorul cand vrea sa vizualizeze toate request-urile pe care le-a adaugat(ca un history)*@
@*ele o sa aiba mai tz si status: accepted, denied, pending (la crearea lor automat iau valoarea pending)*@

@{
    ViewBag.Title = "Index";
}

<br />

<h2 class="text-center">Afisare cereri</h2>

<br />

@if (ViewBag.Message != null)
{
    <div class="@ViewBag.Alert p-3 rounded-3 text-center mb-5">@ViewBag.Message</div>
}
<br />


@*motor de cautare*@
<form method="GET">
    <div class="input-group mb-3">
        <input type="text" class="form-control"
               placeholder="Search topics or keywords" name="search"
               value="@ViewBag.SearchString">
        <button class="btn btn-outline-success"
                type="submit">
            Search
        </button>
    </div>
</form>

@foreach (ProiectV1.Models.Request request in ViewBag.Requests)
{
    <div class="card">
        <div class="card-body">

            <h3 class="card-title alert-success py-3 px-3 rounded-2">@request.Title</h3>

            

            <div class="d-flex justify-content-between flex-row mt-5">

                <div><i class="bi bi-globe"></i> @request.Category.CategoryName</div>

                <a class="btn btn-success" href="/Requests/ShowColaborator/@request.Id">Afisare cerere</a>

                <span class="alert-success">@request.Date</span>

            </div>

        </div>
    </div>
}

<br />
<a class="btn btn-success" href="/Requests/New">Fa o noua cerere pentru un produs</a>
<br />

@* Afisarea paginata a cererilor *@
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link"
                   href="/Requests/IndexColaborator?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= ViewBag.lastPage; i++)
            {
                <li class="page-item">
                    <a class="page-link"
                       href="/Requests/IndexColaborator?page=@i">@(i)</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link"
                   href="/Requests/IndexColaborator?page=@(ViewBag.lastPage)" aria-
                   label="Next">

                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<br />
<br />

ProiectV1/Views/Requests/New.cshtml
@model ProiectV1.Models.Request

<h2 class="text-center mt-5">Adaugare produs nou</h2>

<br />

<div class="container mt-5">
    <div class="row">
        <div class="col-6 offset-3">

            <form enctype="multipart/form-data" asp-controller="Requests" asp-action="New">

                @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                <input class="form-control" placeholder="Titlu Produs" type="text" name="Title" />
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })

                <br />
                <textarea class="summernote" placeholder="Descriere produs" style="width: 100%; height: 100px;" name="Description"></textarea>
                @Html.ValidationMessage("Description", null, new { @class = "text-danger" })

                <br />
                <input class="form-control" placeholder="Pretul Produsului" type="text" name="Price" />
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })

                <br />
                <input type="file" name="ImageFile" class="form-control" />
                @Html.ValidationMessageFor(m => m.PictureUrl, "", new { @class = "text-danger" })

                <br />
                <label>Selectati categoria</label>
                @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categ, "Value", "Text"),
                         "Selectati categoria", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CategoryId, null, new { @class = "text-danger" })

                <br />
                <button class="btn btn-success" type="submit">Adauga produs</button>

            </form>

        </div>
    </div>
</div>

ProiectV1/Views/Requests/ShowAdmin.cshtml
@model ProiectV1.Models.Request

@*Pagina pe care o vede administratorul cand vrea sa vizualizeze un request specific (nu lista cu toate))*@

<br />

<div class="card">

    <div class="card-body">

        <h3 class="card-title alert-success py-3 px-3 rounded-2">@Model.Title</h3>

        @*<div class="card-text">@Model.Description</div>*@
        <div class="card-text">@Html.Raw(Model.Description)</div>
        <br />
        <br />

        <img src="@Model.PictureUrl" alt="Imagine Produs" class="img-fluid" width="300" height="200">
        <br />
        <br />

        <div class="d-flex justify-content-between flex-row mt-3">
            <div><strong>Pret:</strong> @Model.Price</div>
        </div>

        <div class="d-flex justify-content-between flex-row mt-5">

            <div><i class="bi bi-globe"></i> @Model.Category.CategoryName</div>

            <div><i class="bi bi-person"></i> @Model.User.UserName </div>

            <span class="alert-success">@Model.Date</span>

        </div>
        <div class="d-flex justify-content-between flex-row mt-5">

            <div class="d-flex justify-content-between flex-row mt-5">
                <form asp-action="Approve" method="post">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button type="submit" class="btn btn-success">Acceptare cerere</button>
                </form>

                <form asp-action="Reject" method="post">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <button type="submit" class="btn btn-danger">Refuzare cerere</button>
                </form>
            </div>

        </div>


    </div>



</div>

ProiectV1/Views/Requests/ShowColaborator.cshtml
@model ProiectV1.Models.Request

@*Pagina pe care o vede colaboratorul cand vrea sa vizualizeze un request specific (nu lista cu toate))*@

<br />

<div class="card">

    <div class="card-body">

        <h3 class="card-title alert-success py-3 px-3 rounded-2">@Model.Title</h3>

        @*<div class="card-text">@Model.Description</div>*@
        <div class="card-text">@Html.Raw(Model.Description)</div>

        <br />
        <br />
        <img src="@Model.PictureUrl" alt="Imagine Produs" class="img-fluid" width="300" height="200">
        <br />
        <br />

        <span class="justify-content-between flex-row mt-5 alert-success">@Model.Status</span>

        <div class="d-flex justify-content-between flex-row mt-3">
            <div><strong>Pret:</strong> @Model.Price</div>
        </div>
        <div class="d-flex justify-content-between flex-row mt-5">

            <div><i class="bi bi-globe"></i> @Model.Category.CategoryName</div>
            
            <div><i class="bi bi-person"></i> @Model.User.UserName </div>

            <span class="alert-success">@Model.Date</span>

        </div>



    </div>



</div>