ProiectV1/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProiectV1.Data;
using ProiectV1.Models;

namespace ProiectV1.Controllers
{
    //dam dreptul doar adminului pe tot controller-ul (Deoarece toate metodele din controller ar fi tb sa aiba authorie doar pe admin)
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public CategoriesController(
                ApplicationDbContext context,
                UserManager<ApplicationUser> userManager,
                RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        
        //ceea ce vede userul(adica adminul) in pagina categories/index (view-ul principal)
        public IActionResult Index()
        {
            // Alegem sa afisam 5 categorii pe pagina
            int _perPage = 5;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;  //filtram categoriile sortate crescator
            ViewBag.Categories = categories; //stocam categoriile pt a le putea adauga in view


            // Fiind un numar variabil de categorii, verificam de fiecare data utilizand metoda Count()
            int totalItems = categories.Count();

            // Se preia pagina curenta din View-ul asociat
            // Numarul paginii este valoarea parametrului page din ruta /Categories/Index?page=valoare
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3
            // Asadar offsetul este egal cu numarul de categorii care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            // Se preiau categoriile corespunzatoare pentru fiecare pagina la care ne aflam in functie de offset
            var paginatedCategories = categories.Skip(offset).Take(_perPage);

            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem categoriile cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Categories = paginatedCategories;

            return View();
        }

        //CRUD de catre admin

        //Show -> Read
        public ActionResult Show(int id)
        {
            Category category = db.Categories.Find(id); //stocam categoria cu id-ul dat ca parametru
            return View(category); //ii dam return in view pt a o putea vizualiza in front
        }
        

        //New -> Create
        //HttpGet implicit -> ceea ce vede userul pe pagina categories/new
        //(inainte de a se produce crearea categoriei efectiv)
        public ActionResult New()
        {
            //return View();
            //Category cat = new Category();

            return View();
        }

        //procesul de adaugare al unei categorii
        [HttpPost]
        public ActionResult New(Category cat)
        {
            if(ModelState.IsValid)
            {
                db.Categories.Add(cat); //daca formularul e valid, adaugam categoria noua
                db.SaveChanges(); //dam commit

                TempData["message"] = "Categoria a fost adaugata";
                return RedirectToAction("Index"); //redirect in Index
            }
            else
            {
                return View(cat);
            }
        }

        //Edit - Update
        //HttpGet implicit -> ceea ce vede userul pe pagina categories/edit
        //(inainte de a se produce editarea categoriei efectiv)- ceea ce vede user-ul pentru a putea edita
        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id); //stocam categoria cu id-ul respectiv
            return View(category); //returnam view-ul asociat acelei categorii
        }


        //procesul de editare al unei categorii
        [HttpPost]
        public ActionResult Edit(int id, Category requestCategory)
        {
            Category category = db.Categories.Find(id); //stocam categoria cu id-ul respectiv

            if(ModelState.IsValid) //daca datele sunt valide
            {

                category.CategoryName = requestCategory.CategoryName; //schimbam numele categoriei
                db.SaveChanges(); //commit

                TempData["message"] = "Categoria a fost modificata!";
                return RedirectToAction("Index"); //redirect in index cu mesajul asociat
            }
            else
            {
                return View(requestCategory);
            }
        }


        //Delete
        //procesul de stergere al unei categorii
        [HttpPost]
        public ActionResult Delete(int id)
        {
            //se vor adauga ulterior aceste linii cand o sa fie gata partea de product si comments
            Category category = db.Categories.Include("Products")
                                             .Include("Products.Comments")
                                             .Where(c => c.Id == id)
                                             .First();
            //si se va sterge linia asta de mai jos-> deoarece va deveni inutila
            //Category category = db.Categories.Find(id);


            db.Categories.Remove(category); //stergerea categoriei din BD
            TempData["message"] = "Categoria a fost stearsa";
            db.SaveChanges(); //commit
            return RedirectToAction("Index"); //te redirectioneaza pe pagina categories/index
        }
        
    }
}

ProiectV1/Controllers/UsersController.cs
using ProiectV1.Data;
using ProiectV1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ProiectV1.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
            db = context;

            _userManager = userManager;

            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;

            ViewBag.UsersList = users;

            return View();
        }

        public async Task<ActionResult> Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            var roles = await _userManager.GetRolesAsync(user);

            ViewBag.Roles = roles;

            return View(user);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);

            user.AllRoles = GetAllRoles();

            var roleNames = await _userManager.GetRolesAsync(user); // Lista de nume de roluri

            // Cautam ID-ul rolului in baza de date
            var currentUserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Id)
                                              .First(); // Selectam 1 singur rol
            ViewBag.UserRole = currentUserRole;

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, ApplicationUser newData, [FromForm] string newRole)
        {
            ApplicationUser user = db.Users.Find(id);

            user.AllRoles = GetAllRoles();


            if (ModelState.IsValid)
            {
                user.UserName = newData.UserName;
                user.Email = newData.Email;
                user.FirstName = newData.FirstName;
                user.LastName = newData.LastName;
                user.PhoneNumber = newData.PhoneNumber;


                // Cautam toate rolurile din baza de date
                var roles = db.Roles.ToList();

                foreach (var role in roles)
                {
                    // Scoatem userul din rolurile anterioare
                    await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                // Adaugam noul rol selectat
                var roleName = await _roleManager.FindByIdAsync(newRole);
                await _userManager.AddToRoleAsync(user, roleName.ToString());

                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Delete(string id)
        {
            var user = db.Users
                         .Include("Products")
                         .Include("Comments")
                         .Include("Requests")
                         .Where(u => u.Id == id)
                         .First();

            // Delete user comments
            if (user.Comments.Count > 0)
            {
                foreach (var comment in user.Comments)
                {
                    db.Comments.Remove(comment);
                }
            }

            // Delete user bookmarks
            if (user.Requests.Count > 0)
            {
                foreach (var request in user.Requests)
                {
                    db.Requests.Remove(request);
                }
            }

            // Delete user articles
            if (user.Products.Count > 0)
            {
                foreach (var product in user.Products)
                {
                    db.Products.Remove(product);
                }
            }

            db.ApplicationUsers.Remove(user);

            db.SaveChanges();

            return RedirectToAction("Index");
        }


        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();

            var roles = from role in db.Roles
                        select role;

            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }
    }
}

ProiectV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProiectV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProiectV1.styles.css" asp-append-version="true" />

    @*se include summernote.css*@
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Coffee cup-logos_black.png" width="100" height="100" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-5">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina principala</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Produsele noastre</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Afisare Categorii</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="IndexAdmin">Afisare Cereri</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Afisare utilizatori</a>
                            </li>
                           
                        }
                        @if (User.IsInRole("Colaborator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="IndexColaborator">Afisare Cereri</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="New">Cerere noua</a>
                            </li>


                        }
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductShoppingCarts" asp-action="Index">
                                    <header>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-heart-fill" viewBox="0 0 16 16">
                                        <path d="M11.5 4v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m0 6.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132" />
                                    </svg>
                                    </header>
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Coffee Cup - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @*se include summernote.js*@
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Summernote.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>